package day_47_exceptions_continue;

public class CustomException2 {

    public static void main(String[] args) throws InterruptedException {

        // this is checked exception we still have to handle it before we can run our program
        // even though we are throwing manually/explicitly
//        throw new InterruptedException("some message");

        // create an object of the Exception class and throw the object
        //InterruptedException a = new InterruptedException("Message");
        //throw a;


    }
}
